export const PHYSICS = {
  MAX_SPEED: 900,
  MAX_ROTATION_SPEED: 6,
  MANEUVER_THRUST: 200,
  MAIN_ENGINE_THRUST: 450,
  AFTERBURNER_MULT: 2.2,
  BRAKE_MANEUVER_THRUST: 120,
  BRAKE_MAIN_THRUST: 500,
  ROTATION_ACCEL: 12,
  ROTATION_DAMPING: 8,
  VELOCITY_THRESHOLD: 5,
};

export const SHIP = {
  WIDTH: 28,
  HEIGHT: 36,
  CANNON_OFFSET: 22,
  CANNON_COOLDOWN: 0.08,
  PROJECTILE_SPEED: 1200,
  PROJECTILE_DAMAGE: 25,
};

export const WORLD = {
  CHUNK_SIZE: 2000,
  LOAD_RADIUS: 2,
  UNLOAD_RADIUS: 4,
  SEED: 42,
};

export const CAMERA = {
  MAX_OFFSET_RATIO: 0.32,
  OFFSET_SMOOTHING: 4,
  STATIONARY_THRESHOLD: 15,
  ZOOM_MIN: 0.4,
  ZOOM_MAX: 2.0,
  ZOOM_WHEEL_STEP: 0.1,
  ZOOM_SMOOTHING: 6,
  SPEED_ZOOM_MAX: 1.0,
  SPEED_ZOOM_MIN: 0.55,
};

export const RENDER = {
  CIRCLE_MARGIN: 0.08,
};
